### ISSUE TITLE
Can’t find 433_generator folder 

### ISSUE THREAD

**Issue by DIYglenn** [athombv/node-homey-433#4]
It doesn’t work for me. After creating the app through terminal, this generator doesn’t create the necessary 433_generator folder. 
If created manually, it’s missing config.js afterwards.

**Comment by jeroenvollenbrock** [comment]
The 433_generator folder should be manually created as its contents describe the workings of the app it should generate. However, we are currently phasing out the 433 generator and its support in favor of the SDKv2 successor https://github.com/athombv/node-homey-rfdriver
